### ISSUE TITLE
Access error to Notepad window

### ISSUE THREAD

**Issue by bstordrup** [serilog-contrib/serilog-sinks-notepad#24]
I'm using the SeriLog.Sinks.Notepad latest version, but I cannot get it to work.

Usign the SelfLog feature to Console, I get this error:

`2022-03-14T08:47:14.7322195Z Unable to access a Notepad Editor on process Notepad (28836)`

So it does find the process, but it is not able to access it.

**Comment by bash** [comment]
I get the same error. I'm using Windows 11 with the redesigned Notepad.

**Comment by bstordrup** [comment]
Nice, and I see you have a pull request for it. Hope it will get settled soon.

**Comment by augustoproiete** [comment]
That's great! Thank you gents!

@bstordrup Do you confirm that you're also using Windows 11 when you see that error? Wondering if @bash's PR fixes your case too, of if we have another issue to investigate

**Comment by bstordrup** [comment]
@augustoproiete, yes, I'm using Windows 11 as well, so @bash's PR will fix my issue. But as soon as a new package is available, I will test it.

**Comment by augustoproiete** [comment]
:tada: The changes implemented in response to this issue shipped with **Serilog.Sinks.Notepad v2.1.0**

The release is available on:

- :rocket: [GitHub Release](https://github.com/serilog-contrib/serilog-sinks-notepad/releases/tag/v2.1.0)
- :package: [NuGet Package](https://www.nuget.org/packages/Serilog.Sinks.Notepad/2.1.0)
